In [1]:
import numpy

In [17]:
# numpy 배열끼리의 암산

## #02 기초 통계량 산출

### [1] 1차원 데이터의 경우

#### 1 샘플데이터

In [2]:
myarr = numpy.array([98, 72, 80, 64])
myarr

array([98, 72, 80, 64])

$\Omega$              : 모집단


$\mu$                 : 모평균


$\sigma^2$          : 모분산


$\sigma$            


$\bar{X}$

$s^2$

$s$

$n$

$\sum$




In [5]:
print("최대값:", numpy.max(myarr))

print("최소값:", numpy.min(myarr))
print("합계값:", numpy.sum(myarr))
print("평균:", numpy.average(myarr))

최대값: 98
최소값: 64
합계값: 314
평균: 78.5


### 분산 , 표준편차

#### 편차($d$)
 관측($y$)값(=실제값, 조사된 값)에서 평균($\bar{y}$)을 뺀값

* markdown에서 "$"로 문자열을 감싸면 수식으로 바꿔줌 

$편차 = 관측값 - 평균$


$d = y - \bar{y}$

#### 분산
 편차 제곱의 평균

 $ \sigma^2 = \bar{d^2}$

#### 표준편차


In [14]:
print("분산:", numpy.var(myarr))
print("표준편차:", numpy.std(myarr) )

분산: 158.75
표준편차: 12.599603168354152


$\Omega$ 
오메가: 모집단

$\mu$
뮤: 모평균(모집단의 평균, 모수)



In [18]:
import numpy as np

In [19]:
# 위치 (인덱스)가 동일한 원소끼리 수행된다.
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [20]:
a = arr1 + arr2
a

array([12, 18, 24, 30, 36])

In [21]:
b = arr1 - arr2
b

array([ 8, 12, 16, 20, 24])

In [22]:
c = arr1 * arr2
c

array([ 20,  45,  80, 125, 180])

In [23]:
d = arr1 / arr2
d

array([5., 5., 5., 5., 5.])

In [24]:
# 위치 (인덱스)가 동일한 원소끼리 수행된다.
arr1 = np.array([10, 15, 20, 25, 30])
arr2 = np.array([2,3,4,5,6])
print(arr1)
print(arr2)

[10 15 20 25 30]
[2 3 4 5 6]


In [25]:
a = np.add(arr1, arr2) # add 덧셈
a

array([12, 18, 24, 30, 36])

In [26]:
b = np.subtract(arr1, arr2) # subtarct 뺄셈
b

array([ 8, 12, 16, 20, 24])

In [27]:
c = np.multiply(arr1, arr2) # multiply 곱셈
c

array([ 20,  45,  80, 125, 180])

In [28]:
d = np.divide(arr1, arr2) # devide 나눗셈
d

array([5., 5., 5., 5., 5.])

In [29]:
grade = np.array([82, 77, 91, 88])
grade

array([82, 77, 91, 88])

In [30]:
# 추출하고자 하는 원본과 같은 사이즈의 배열을 생성한다 추출할 값은 True, 추출하지않을 값은 False

bool_array = np.array([True, True, False, True])
bool_array

array([ True,  True, False,  True])

In [31]:
# 조건에 맞는 항목만 1차 배열로 추출
result1 = grade[bool_array]
result1

array([82, 77, 88])

In [32]:
## 조건에 맞는 원소 추출
# 80 점 이상인 원소를 추출하기 -> 대괄호 : where

result2 = grade[grade >= 80]
result2

array([82, 91, 88])

In [33]:
# 80점 이상이고 90점 이하인 데이터만 추려냄 -> 비교연산자 앞에 logical 메서드 

result3 = grade[np.logical_and(grade >= 80 , grade <= 90)]
result3 

array([82, 88])

In [34]:
# 80점 미만이거나 90점 초과인 데이터만 추려냄

result4 = grade[np.logical_or(grade<80, grade>90)]
result4

array([77, 91])

In [36]:
grade = np.array([81, 97, 75])

result1 = grade[grade >= 80]

result2 = grade[np.logical_and(grade>70, grade<90)]

result3 = grade[np.logical_or(grade<80, grade >=90)]


print(grade)
print(result1)
print(result2)
print(result3)

[81 97 75]
[81 97]
[81 75]
[97 75]
