# 도수

특정한 구간 또는 범주에 속하는 자료의 개수

예를 들어, 어떤 학급의 학생들의 시험 점수를 기록한다면 각 점수 대역에 속하는 학생의
수를 세어 도수를 구할 수 있다.


도수 분포표

도수들을 정리하여 국간별 도수를 표로 나타낸 것

도수분포는 평균, 중앙값, 최빈값과 같은 중심경향성 통계량을 계산하거나 자료의 분산과 
퍼짐 정도를 파악하는 데에도 사용된다.

이를 통해 데이터의 특성을 더 잘 이해하고 추론할 수 있다.



In [1]:
### 준비과정

### 패키지 참조

import numpy as np

In [2]:
point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])
point

array([100,  91,  89,  86,  84,  79,  78,  77,  74,  71,  69,  66,  65,
        60,  58,  57,  55])

히스토그램(histogram): 

> 도수분포도를 정보 그림의 한 눈에 보기 쉽게 표현한것

In [4]:
hist, bins = np.histogram(point, 5)

print("구간별 데이터 수:",hist)
print("구간별 경계:", bins)

구간별 데이터 수: [4 4 4 3 2]
구간별 경계: [ 55.  64.  73.  82.  91. 100.]


In [5]:
# 데이터 구간 개수로 나누기


In [7]:
# 데이터 구간을 직접 정의하기

hist, bins = np.histogram(point, [50, 60, 70, 80, 90, 100])


print("구간별 데이터 수:",hist)
print("구간별 경계:", bins)

구간별 데이터 수: [3 4 5 3 2]
구간별 경계: [ 50  60  70  80  90 100]


# 도수

## 특정한 구간 또는 범주에 속하는 자료의 개수

### ex: 어떤 학급의 학생들의 시험 점수를 기록한다면 각 점수 대역에 속하는 학생의 수를 세어 도수를 구할 수 있다

도수 분포표

도수들을 정리하여 구간별 도수를 표로 나타낸 것

도수분포는 평균, 중앙값, 최빈값과 같은 중심경향성(데이터의 중심이 어디있는 지를 나타내는 지표) 통계량을 계산하거나 자료의 분산과 퍼짐 정도를 파악하는 데에도 사용된다.
이를 통해 데이터의 특성을 더 잘 이해하고 추론할 수 있다.

In [2]:
import numpy as np

In [3]:
# 샘플 데이터

point = np.array([100, 91, 89, 86, 84, 79, 78, 77, 74, 71, 69, 66, 65, 60, 58, 57, 55])

point

array([100,  91,  89,  86,  84,  79,  78,  77,  74,  71,  69,  66,  65,
        60,  58,  57,  55])

In [5]:
# Numpy의 histogradm : 도수분포도를 표형식으로 표현한것
# [1] 5개의 구간으로 나누기 (범위는 함수내에서 임의적으로 생성됨)

b = np.histogram(point, 5)



print("구간 경계:", b)

구간 경계: (array([4, 4, 4, 3, 2], dtype=int64), array([ 55.,  64.,  73.,  82.,  91., 100.]))


In [6]:
# 도수 분포표 구성

s = len(a)
for i in range(0, s):
    if i + 1 < s:
        tpl = "%d이상 %d미만: %d개"
    else:
        tpl = "%d이상 %d이하: %d개"

    print(tpl % (b[i], b[i+1], a[i])) 


55이상 64미만: 4개
64이상 73미만: 4개
73이상 82미만: 4개
82이상 91미만: 3개
91이상 100이하: 2개


In [7]:
# [2] 데이터 구간을 직접 정의하기

hist, bins = np.histogram(point, [50, 60, 70, 80, 90, 100])

print("구간별 데이터 수:", a)
print("구간 경계:", b)

구간별 데이터 수: [4 4 4 3 2]
구간 경계: [ 55.  64.  73.  82.  91. 100.]


절대 도수

어떠한 변수에 대한 실제 빈도수

`np.histogram()` 에서 리턴하는 `hist`값이 절대도수임

상대도수

절대도수를 백분률로 환산한 값

각 도수를 도수의 총 합으로 나눈 값

In [8]:
relative_freq = a / np.sum(a)
relative_freq

array([0.23529412, 0.23529412, 0.23529412, 0.17647059, 0.11764706])

In [9]:
# 누적 도수

# 절대도수에서 자기 앞 도수를 모두 다 더한 값

In [10]:
cum = []

previous = 0

for i in hist:
    previous += i
    cum.append(previous)

cum

[3, 7, 12, 15, 17]