In [1]:
# 2차원 배열

In [2]:
import numpy as np

In [32]:
# 2차원 배열의 생성

## 철수의 학년 - 과목별 점수

grade = np.array([
    [98, 72, 80, 64],
    [88, 90, 80, 72],
    [92, 88, 82, 5]
])
grade

array([[98, 72, 80, 64],
       [88, 90, 80, 72],
       [92, 88, 82,  5]])

In [27]:
## 2차원 배열의 크기


### 차원 크기

grade.ndim

2

In [28]:
# 각 차원별 원소수

grade.shape

(3, 4)

In [8]:
# 원소의 데이터 타입

grade.dtype

dtype('int32')

In [9]:
# 2차원 배열의 기초 통계량

### 결과 타입은 numpy의 1차 배열

In [10]:
## 각 열끼리 더함(세로로 덧셈)

s1 = np.sum(grade, axis = 0)
s1

array([278, 250, 242, 212])

In [11]:
## 각 행끼리 더함(가로로 덧셈)

s2 = np.sum(grade, axis = 1)
s2

array([314, 330, 338])

In [14]:
# 조건 검색

# (1) bollean 타입으로 인덱싱

## 조건에 맞는 값들을 1차원으로 반환한다

bool_array = np.array([
    [True, False, True, False],
    [True, True, True, False],
    [False, True, True, False]
])

result1 = grade[bool_array]
result1

array([98, 80, 88, 90, 80, 88, 82])

In [15]:
# and 검색

result2 = grade[np.logical_and(grade >= 80, grade<= 90)]

result2

array([80, 88, 90, 80, 88, 82])

In [16]:
# or 검색

result3 = grade[np.logical_or(grade<70, grade>80)]
result3

array([98, 64, 88, 90, 92, 88, 82])

In [17]:
## 정형화된 배열 생성하기

### 모든 원소가 0인 배열

np.zeros([3, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
#### 모든 원소가 1인 배열

np.ones([3, 4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#### 모든 원소가 특정값인 배열

np.full([3, 4], 500)

array([[500, 500, 500, 500],
       [500, 500, 500, 500],
       [500, 500, 500, 500]])

In [22]:
## 단위 행렬 만들기
##> 대각선으로 1이고 나머지 원소는 모드 0인 배열

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
arr1 = np.array([10, 20, 30])
arr2 = np.array([5, 7])

arr3 = arr1 + arr2

arr3

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [25]:
## 랜덤 배열

### [1] `0`부터 `1`의 범위에서 균등하게 추출하여 N차원 배열을 생성한다

np.random.rand(10)

array([0.60750397, 0.04670674, 0.2939818 , 0.77176563, 0.83321009,
       0.18031288, 0.77017534, 0.82803826, 0.9282405 , 0.95850496])

In [26]:
np.random.rand(5)

array([0.43911518, 0.78383033, 0.43415835, 0.71214712, 0.38710186])

In [77]:
np.random.randint(0, 9, 10)

array([5, 0, 0, 4, 2, 1, 7, 8, 2, 7])

In [78]:
# 표준 정규 분포를 따르는 랜덤 배열

### 1차원 배열

np.random.randn(10)

array([ 0.16125333, -0.85186235,  0.98912589, -0.13494606,  0.03342433,
        0.84844076, -0.52996437,  1.00845816, -0.3629193 ,  1.30272822])

In [80]:
### 2차원 배열

np.random.randn(4,3)

array([[ 0.94135448,  0.57288024,  1.37158028],
       [-0.94951621, -0.71044329, -0.12100425],
       [ 0.86669164,  2.45540917, -1.12669286],
       [ 1.74030421, -0.09822566,  0.42331315]])

In [81]:

## 정규 분포를 직접 설정


### 1차원 배열

# 평균은 `0`, 표준편차`1`의 정규 분포에서 10개의 수를 추출

In [83]:
np.random.normal(0, 1, (3, 4))

array([[ 1.34483605,  1.40564187,  0.05861023, -0.41111661],
       [-1.01239847,  0.19201982, -0.05212499,  0.14231435],
       [ 0.49079257,  0.8639976 , -1.00396002,  0.75894906]])

In [91]:
# 랜던값 고정 -> seed : 타짜의 탄, 미리 정해진 랜던함 순서의 세트

# 랜덤이란 사전에 잘 섞여 있는 숫자 셋을 순차적으로 꺼내는 것을 의미

# 랜덤시드는 몇 번째 숫자 셋인지를 의미하는 값

# 이 값을 고정하면 특정 숫자 셋만 사용하라는 의미

np.random.seed(1234)
np.random.normal(0, 1, (4, 3))

array([[ 0.47143516, -1.19097569,  1.43270697],
       [-0.3126519 , -0.72058873,  0.88716294],
       [ 0.85958841, -0.6365235 ,  0.01569637],
       [-2.24268495,  1.15003572,  0.99194602]])

In [117]:
np.random.normal(0, 1, (4, 3))

array([[ 0.52704645,  0.7111124 , -0.21754548],
       [ 2.63779121, -1.74213763, -0.09443481],
       [ 1.43118375,  0.59275845,  0.1702969 ],
       [-1.75170595,  0.28858132, -0.54257952]])